project:
  type: website
  output-dir: ../docs

website:
  title: "EU Omnibus Briefing"
  repo-url: https://github.com/clairembassett/EEUOmnibus.git
  repo-branch: master

  sidebar:
    search: true

  navbar:
    search: true
    left:
      - href: index.qmd
        text: Introduction
      - href: purpose.qmd
        text: Purpose
      - href: keyterms.qmd
        text: Key Terms
      - href: approvedchanges.qmd
        text: Approved Changes
      - text: Proposed Changes
        menu:
          - href: proposedchanges.qmd
            text: Overview
          - href: propcsrd.qmd
            text: CSRD
          - href: propcsddd.qmd
            text: CSDDD
          - href: propeutax.qmd
            text: EU Taxonomy
          - href: propcbam.qmd
            text: CBAM
      - text: Client Application
        menu:
          - href: clientapplication.qmd
            text: Client A
      - href: seceffects.qmd
        text: Secondary Effects to ETS
      - href: cbamcalc.qmd
        text: CBAM Calculator
      - href: sources.qmd
        text: Bibliography

format:
  html:
    embed-resources: true
    theme:
      - flatly
    css: styles.css
    toc: true