project:
  type: website
  output-dir: ../docs

website:
  title: "EU Omnibus Briefing"
  repo-url: https://github.com/clairembassett/EEUOmnibus.git
  repo-branch: master

  sidebar:
    search: true

  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - href: purpose.qmd
        text: Purpose
      - href: keyterms.qmd
        text: Key Terms
      - href: approvedchanges.qmd
        text: Approved Changes
      - href: proposedchanges.qmd
        text: Proposed Changes
      - href: clientapplication.qmd
        text: Client Application
      - href: secaffects.qmd
        text: Secondary Affects to ETS
      - href: sources.qmd
        text: Bibliography

format:
  html:
    embed-resources: true
    theme:
      - Flatly
    css: styles.css
    toc: true
    


    



